### ISSUE TITLE
enum34 should be conditionally included.

### ISSUE THREAD

**Issue by dsully** [ManrajGrover/py-log-symbols#14] opened 2018-03-11 05:24 UTC
enum34 should be conditionally included, as Python 3.4+ already has this module.

**Comment by makkus** [comment] 2019-04-13 13:57
This does not work for me. Using Python 3.6, and getting erros due to enum34 being installed.
It seems having a conditional statement in setup.py is not a good idea, it'd be better to use something like:

    extras_require = {
      ":python_version<'3.4'": ['enum34'],
    }

(requires a relatively recent version of setuptools, if I'm not mistaken)

References:

https://github.com/robshakir/pyangbind/issues/232
https://gitlab.com/pycqa/flake8/merge_requests/191/diffs

**Comment by manrajgrover** [comment] 2019-04-18 20:56
@makkus Hi, thanks for bringing it up. I don't see this breaking in Travis. Also, I don't see `log_symbols` package installing enum34 for Python 3.6.

Reference: https://travis-ci.org/manrajgrover/py-log-symbols/jobs/423113624#L446

Can you double check if `enum34` was actually installed by this package and that your setuptools is on the latest version?

**Comment by makkus** [comment] 2019-04-19 00:15
Hi @manrajgrover, thanks for looking into this, much appreciated! As far as I understand, the problem is that it sometimes works, but is not reliable. I'm not 100% sure what causes it to break, I suspect it has something to do with the system python, or how a virtualenv is created.

Anyhow, I just created a venv using pyenv, here's the log:

```
➜ pyenv virtualenv 3.6.8 log_symbols_venv
Looking in links: /tmp/tmpc5a1kmbh
Requirement already satisfied: setuptools in /home/markus/.pyenv/versions/3.6.8/envs/log_symbols_venv/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /home/markus/.pyenv/versions/3.6.8/envs/log_symbols_venv/lib/python3.6/site-packages (18.1)

inaugurate on  freck [!] took 3s 
➜ . ~/.pyenv/versions/log_symbols_venv/bin/activate

inaugurate on  freck [!] via log_symbols_venv 
➜ pip install log_symbols
Collecting log_symbols
Collecting enum34==1.1.6 (from log_symbols)
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Collecting colorama==0.3.9 (from log_symbols)
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Installing collected packages: enum34, colorama, log-symbols
Successfully installed colorama-0.3.9 enum34-1.1.6 log-symbols-0.0.12
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


```

Updating setuptools and pip before the install doesn't seem to help either:

```
➜ pyenv virtualenv 3.6.8 log_symbols_venv_2 
Looking in links: /tmp/tmpd66kow_z
Requirement already satisfied: setuptools in /home/markus/.pyenv/versions/3.6.8/envs/log_symbols_venv_2/lib/python3.6/site-packages (40.6.2)
Requirement already satisfied: pip in /home/markus/.pyenv/versions/3.6.8/envs/log_symbols_venv_2/lib/python3.6/site-packages (18.1)

inaugurate on  freck [!] took 3s 
➜ . ~/.pyenv/versions/log_symbols_venv_2/bin/activate

inaugurate on  freck [!] via log_symbols_venv_2 
➜ pip install -U pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.0.3

inaugurate on  freck [!] via log_symbols_venv_2 took 16s 
➜ pip install -U setuptools
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/c8/b0/cc6b7ba28d5fb790cf0d5946df849233e32b8872b6baca10c9e002ff5b41/setuptools-41.0.0-py2.py3-none-any.whl
Installing collected packages: setuptools
  Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
Successfully installed setuptools-41.0.0

inaugurate on  freck [!] via log_symbols_venv_2 took 2s 
➜ pip install log_symbols                           
Collecting log_symbols
Collecting colorama==0.3.9 (from log_symbols)
  Using cached https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting enum34==1.1.6 (from log_symbols)
  Using cached https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
Installing collected packages: colorama, enum34, log-symbols
Successfully installed colorama-0.3.9 enum34-1.1.6 log-symbols-0.0.12

```

So, again, not sure what exactly triggers the issue, but it seems a generally accepted way of doing this is the extras_require way.

**Comment by makkus** [comment] 2019-04-21 11:30
Apologies, I didn't realize the original fix wasn't released yet, it looks like I still was using 0.0.12 which does not have any conditional enum34 code included.

Either way, I still think it'd be a good idea to use the 'extras_require' option as that seems to produce consistent metadata for a Python package, independent of the Python version it is build with. When having the conditional statement in, the requirements list in the package metadata will depend on the version at build time.

**Comment by manrajgrover** [comment] 2019-05-29 08:22
@makkus I apologize for the delay.

I've released [`v0.0.13`](https://pypi.org/project/log-symbols/0.0.13/) which should fix this. Can you please check now?

**Comment by manrajgrover** [comment] 2019-06-03 15:55
@makkus This should be fixed now. Please try the new version and let me know if you face any issue. Closing this.

**Closed as completed by manrajgrover** 2019-06-03 15:55 UTC

**Comment by makkus** [comment] 2019-06-03 15:58
Hi @manrajgrover , sorry for not getting back earlier, bit snowed under. After quick testing, yes, seems to work now. Thanks!
